version: '3.8'

services:
  flask-app:
    build:
      context: .  # Build the Docker image from the current directory
    container_name: flask_app_container
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
