services:
  flask-app:
    build:
      context: .  # Use the current directory as the build context
    container_name: mitlas-marine-flask_app_container
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    environment:
      FLASK_ENV: production  # Set environment to production
    volumes:
      - .:/app  # Mount the current directory to /app inside the container (useful for development)
